#!/usr/bin/env bash
#
# Athena Accounting — installer
#
# Generates a .env file with cryptographically random secrets.
# Idempotent: refuses to overwrite an existing .env unless --force is passed.
#
# Usage:
#   ./install.sh          # safe: bail out if .env already exists
#   ./install.sh --force  # overwrite .env (a timestamped backup is kept)

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$SCRIPT_DIR"

FORCE=0
for arg in "$@"; do
  case "$arg" in
    --force|-f)
      FORCE=1
      ;;
    --help|-h)
      sed -n '3,12p' "$0" | sed 's/^# \{0,1\}//'
      exit 0
      ;;
    *)
      echo "Argument inconnu: $arg" >&2
      echo "Utilisation: $0 [--force]" >&2
      exit 2
      ;;
  esac
done

if ! command -v openssl >/dev/null 2>&1; then
  echo "Erreur: openssl est requis pour générer les secrets." >&2
  exit 1
fi

if [[ -f .env ]]; then
  if [[ $FORCE -eq 0 ]]; then
    echo "Le fichier .env existe déjà — rien à faire."
    echo "Pour le régénérer (les secrets actuels seront perdus): ./install.sh --force"
    exit 0
  fi
  read -r -p "Écraser .env ? Les secrets actuels seront perdus. [y/N] " ans
  case "$ans" in
    y|Y|yes|YES|oui|OUI) ;;
    *) echo "Annulé." ; exit 0 ;;
  esac
  backup=".env.backup.$(date +%Y%m%d-%H%M%S)"
  cp .env "$backup"
  echo "Sauvegarde de l'ancien .env -> $backup"
fi

# 32 URL-safe chars from openssl base64 — strip padding/slashes/newlines.
# That's ~192 bits of entropy, well above what Postgres needs.
rand_password() {
  openssl rand -base64 48 | tr -d '=+/\n' | cut -c1-32
}

# 64 hex chars = 256 bits — well above the 32-char minimum we enforce in env.ts.
rand_hex() {
  openssl rand -hex 32
}

POSTGRES_USER="${POSTGRES_USER:-athena}"
POSTGRES_DB="${POSTGRES_DB:-athena}"
POSTGRES_PASSWORD="$(rand_password)"
SESSION_SECRET="$(rand_hex)"
BACKEND_PORT="${BACKEND_PORT:-3000}"
COOKIE_SECURE="${COOKIE_SECURE:-false}"

# umask 077 also restricts the temp write; chmod afterwards is belt + braces.
umask 077

cat > .env <<EOF
# Generated by install.sh on $(date -u +"%Y-%m-%dT%H:%M:%SZ")
# DO NOT commit this file. Secrets are random and unique to this install.

POSTGRES_USER=$POSTGRES_USER
POSTGRES_PASSWORD=$POSTGRES_PASSWORD
POSTGRES_DB=$POSTGRES_DB

SESSION_SECRET=$SESSION_SECRET

BACKEND_PORT=$BACKEND_PORT
COOKIE_SECURE=$COOKIE_SECURE
EOF

chmod 600 .env

echo
echo "OK: .env généré (permissions 600)."
echo "  Postgres user : $POSTGRES_USER"
echo "  Postgres db   : $POSTGRES_DB"
echo "  Backend port  : 127.0.0.1:$BACKEND_PORT"
echo
echo "Prochaine étape:"
echo "  docker compose up --build"
echo
echo "Au premier accès à http://127.0.0.1:$BACKEND_PORT, l'application"
echo "vous proposera de créer votre identifiant et votre mot de passe."
